server:
  port: 8084

spring:
  application:
    name: card-service
  datasource:
    url: jdbc:postgresql://localhost:5435/carddb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true